### ISSUE TITLE
4.2.2模拟器打开就崩

### ISSUE THREAD

**Issue by duanfb** [danxinzhicheng/IThouse#2]
5:14:52.966 9224-9224/? E/CrashReport: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.danmo.ithouse/com.danmo.ithouse.activity.MainActivity}: android.view.InflateException: Binary XML file line #35: Error inflating class TextView
                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2204)
                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2254)
                                                  at android.app.ActivityThread.access$600(ActivityThread.java:141)
                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
                                                  at android.os.Handler.dispatchMessage(Handler.java:99)
                                                  at android.os.Looper.loop(Looper.java:137)
                                                  at android.app.ActivityThread.main(ActivityThread.java:5069)
                                                  at java.lang.reflect.Method.invokeNative(Native Method)
                                                  at java.lang.reflect.Method.invoke(Method.java:511)
                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
                                                  at dalvik.system.NativeStart.main(Native Method)
                                               Caused by: android.view.InflateException: Binary XML file line #35: Error inflating class TextView

**Comment by danxinzhicheng** [comment]
Hey，你的模拟器是什么版本的？怀疑是5.0以下的哦。

**Comment by duanfb** [comment]
标题已说明，Android4.2.2模拟器

**Comment by danxinzhicheng** [comment]
看到了，代码里大量有关于Material Design的API，所以不支持4.4以及4.4以下的哦

**Comment by duanfb** [comment]
@danxinzhicheng 应该不是的，Material Design的API你也是引入库，我装其他依靠Material Design的app都可以运行的

**Comment by danxinzhicheng** [comment]
你说的是对的，库是编译到代码里了，麻烦用最新的代码再报错一次，我这bugly后台看一下日志。
